# name: Release
# on:
#   push:
#     branches:
#       - main
# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Setup Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '16'
#           registry-url: 'https://registry.npmjs.org'
#       - name: Install dependencies
#         run: yarn --pure-lockfile
#       - name: Build the project
#         run: yarn build
#       - name: Create .npmrc file
#         env:
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#         run: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > .npmrc
#       - name: Relase
#         run: npm publish --access public
